#!/usr/bin/env node
// scripts/ingestAi.js
// Reads AI output in numbered-text format (from a file argument or stdin),
// parses it into the sampleCards JSON structure, and writes
// `src/data/ai_generated_cards.js`.

import fs from "fs";
import path from "path";

async function readInput() {
  const arg = process.argv[2];
  if (arg) return fs.readFileSync(arg, "utf8");
  if (process.stdin.isTTY) return "";
  return await new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => (data += chunk));
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", (err) => reject(err));
  });
}

/**
 * Parse the numbered-text format into a cards array.
 *
 * Expected format:
 *   1. Question text?
 *   a) Option A
 *   b) Option B
 *   c) Option C
 *   answer: b
 */

function parseTextToCards(text) {
  if (!text || typeof text !== "string") return null;

  const blocks = text.split(/(?=^\s*\d+\.\s)/m).filter((b) => b.trim());
  if (blocks.length === 0) return null;

  const cards = [];

  for (const block of blocks) {
    const trimmed = block.trim();

    const questionMatch = trimmed.match(/^\s*\d+\.\s*(.+)/);
    if (!questionMatch) continue;
    const question = questionMatch[1].trim();

    const optionMatches = [...trimmed.matchAll(/^\s*([a-z])\)\s*(.+)/gm)];
    const options = optionMatches.map((m) => ({
      letter: m[1],
      text: m[2].trim(),
    }));

    const answerMatch = trimmed.match(/^\s*answer:\s*([a-z])/im);
    if (!answerMatch || options.length === 0) continue;

    const answerLetter = answerMatch[1].toLowerCase();
    const answerOption = options.find((o) => o.letter === answerLetter);
    const answer = answerOption ? answerOption.text : options[0].text;

    cards.push({
      id: cards.length + 1,
      question,
      answer,
      options: options.map((o) => o.text),
    });
  }

  return cards.length > 0 ? cards : null;
}

function writeCardsFile(cards) {
  const targetDir = path.resolve(process.cwd(), "src", "data");
  if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });
  const outPath = path.join(targetDir, "ai_generated_cards.js");
  const content = `// Auto-generated by scripts/ingestAi.js\nexport const sampleCards = ${JSON.stringify(cards, null, 2)};\n`;
  fs.writeFileSync(outPath, content, "utf8");
  return outPath;
}

async function main() {
  try {
    const raw = await readInput();
    if (!raw || !raw.trim()) {
      console.error(
        "No input provided. Usage: node scripts/ingestAi.js <file> OR pipe text into the script",
      );
      process.exit(2);
    }

    const cards = parseTextToCards(raw);
    if (!cards || cards.length === 0) {
      console.error(
        "Could not parse any flashcards from the input. Expected numbered format:\n  1. Question?\n  a) ...\n  b) ...\n  c) ...\n  answer: b",
      );
      process.exit(3);
    }

    const out = writeCardsFile(cards);
    console.log(`Wrote ${cards.length} cards to ${out}`);
  } catch (err) {
    console.error("Ingest failed:", err);
    process.exit(1);
  }
}

main();
